// Code generated by MockGen. DO NOT EDIT.
// Source: ../clients/garbage-collector/client.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// GarbageCollectorMock is a mock of Client interface.
type GarbageCollectorMock struct {
	ctrl     *gomock.Controller
	recorder *GarbageCollectorMockMockRecorder
}

// GarbageCollectorMockMockRecorder is the mock recorder for GarbageCollectorMock.
type GarbageCollectorMockMockRecorder struct {
	mock *GarbageCollectorMock
}

// NewGarbageCollectorMock creates a new mock instance.
func NewGarbageCollectorMock(ctrl *gomock.Controller) *GarbageCollectorMock {
	mock := &GarbageCollectorMock{ctrl: ctrl}
	mock.recorder = &GarbageCollectorMockMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *GarbageCollectorMock) EXPECT() *GarbageCollectorMockMockRecorder {
	return m.recorder
}

// Counter mocks base method.
func (m *GarbageCollectorMock) Counter(metricName string, metricValue int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Counter", metricName, metricValue)
	ret0, _ := ret[0].(error)
	return ret0
}

// Counter indicates an expected call of Counter.
func (mr *GarbageCollectorMockMockRecorder) Counter(metricName, metricValue interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Counter", reflect.TypeOf((*GarbageCollectorMock)(nil).Counter), metricName, metricValue)
}

// Gauge mocks base method.
func (m *GarbageCollectorMock) Gauge(metricName string, metricValue float64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Gauge", metricName, metricValue)
	ret0, _ := ret[0].(error)
	return ret0
}

// Gauge indicates an expected call of Gauge.
func (mr *GarbageCollectorMockMockRecorder) Gauge(metricName, metricValue interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Gauge", reflect.TypeOf((*GarbageCollectorMock)(nil).Gauge), metricName, metricValue)
}
