// Code generated by MockGen. DO NOT EDIT.
// Source: ../metricsCollector/metrics-collector.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	memstorage "github.com/chikiryau3/garbage-collector/internal/memStorage"
	gomock "github.com/golang/mock/gomock"
)

// MetricsCollectorMock is a mock of MetricsCollector interface.
type MetricsCollectorMock struct {
	ctrl     *gomock.Controller
	recorder *MetricsCollectorMockMockRecorder
}

// MetricsCollectorMockMockRecorder is the mock recorder for MetricsCollectorMock.
type MetricsCollectorMockMockRecorder struct {
	mock *MetricsCollectorMock
}

// NewMetricsCollectorMock creates a new mock instance.
func NewMetricsCollectorMock(ctrl *gomock.Controller) *MetricsCollectorMock {
	mock := &MetricsCollectorMock{ctrl: ctrl}
	mock.recorder = &MetricsCollectorMockMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MetricsCollectorMock) EXPECT() *MetricsCollectorMockMockRecorder {
	return m.recorder
}

// GetMetric mocks base method.
func (m *MetricsCollectorMock) GetMetric(name string) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMetric", name)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMetric indicates an expected call of GetMetric.
func (mr *MetricsCollectorMockMockRecorder) GetMetric(name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMetric", reflect.TypeOf((*MetricsCollectorMock)(nil).GetMetric), name)
}

// ReadStorage mocks base method.
func (m *MetricsCollectorMock) ReadStorage() (*memstorage.StorageData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadStorage")
	ret0, _ := ret[0].(*memstorage.StorageData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadStorage indicates an expected call of ReadStorage.
func (mr *MetricsCollectorMockMockRecorder) ReadStorage() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadStorage", reflect.TypeOf((*MetricsCollectorMock)(nil).ReadStorage))
}

// SetCount mocks base method.
func (m *MetricsCollectorMock) SetCount(name string, value int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetCount", name, value)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetCount indicates an expected call of SetCount.
func (mr *MetricsCollectorMockMockRecorder) SetCount(name, value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetCount", reflect.TypeOf((*MetricsCollectorMock)(nil).SetCount), name, value)
}

// SetGauge mocks base method.
func (m *MetricsCollectorMock) SetGauge(name string, value float64) (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetGauge", name, value)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetGauge indicates an expected call of SetGauge.
func (mr *MetricsCollectorMockMockRecorder) SetGauge(name, value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetGauge", reflect.TypeOf((*MetricsCollectorMock)(nil).SetGauge), name, value)
}
